### ISSUE TITLE
The Pillager Temple keeps spawning near the new world spawn location

### ISSUE THREAD

**Issue by Greg727** [SmartStreamLabs/Create-Pillager-Arise#1]
every time I create a new world The Pillager Temple, the structure that looks like a Japanese style temple, keeps spawning near my location whenever I first load into a world.

I'm not sure if that's intentional or not.

**Comment by SmartStreamLabs** [comment]
Hello, Very sorry that you are experiencing this. May I ask which mod version you are playing on and which Forge version: 1.20.1 / 1.19.2?

We do not experience this problem in our test servers. Hopefully we can resolve this for you quickly.

**Comment by Greg727** [comment]
1.20.1

For some reason a structure always spawns near my spawn point whenever I first load into a world

**Comment by SmartStreamLabs** [comment]
Clearly, this is clearly a bug. I'm going to pin this page as a bug. and hopefully we can fix this in the next update!

Thank you again, and we will keep you informed.

**Comment by SmartStreamLabs** [comment]
Hopefully we have fixed the bug and the version is online on curseforge (link below)

I'm closing this ticket, and feel free to open a new one if you still found a problem.

Link: https://www.curseforge.com/minecraft/mc-mods/create-pillager-arise/files/5695081
