### ISSUE TITLE
Version 1.20.1 - Can't find any buildings

### ISSUE THREAD

**Issue by Swifty744** [SmartStreamLabs/Create-Pillager-Arise#2]
I put the mod in my pack, it's got create + this mod and I loaded two worlds and simply can't find any buildings. If you want to add me on DC or for me to screenshare and show you let me know

**Comment by SmartStreamLabs** [comment]
Hello! Sorry you don't find anything. do you use biome mods? (biome O' Plenty etc)

Option: 2

Other structure mods block our mod.

**Comment by Swifty744** [comment]
None what so ever. I tried with BOP but also deleted all of them and nothing seems to work. Add me on discord NewJerseybaby

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SmartStreamLabs** [comment]
Unfortunately, we are currently not adding anyone on Discord and we handle everything via GitHub.


About the problem: we have run a test several times on forge 1.20.1 and everything works in terms of locate and structure generation.

Do you use a modpack?

**Comment by Swifty744** [comment]
https://prnt.sc/RP8ovAG4iM_z

I am using a testing modpack, something I created.

**Comment by SmartStreamLabs** [comment]
With so few mods it should work indeed. strange, what we do know is that the latest create version blocks/destroys all addons.

Could you try downgrading the create mod and then retesting?

Hopefully that's the problem. :)

https://www.curseforge.com/minecraft/mc-mods/create/files/4835191

**Comment by Swifty744** [comment]
Okay I understand. It's fixed. I found a structure straight away. It was to do with the version of create. I downgraded 2 versions and works fine. Thanks!

**Comment by SmartStreamLabs** [comment]
No problem! Feel free to contact if you have any bugs. 

- SmartStreamLabs
